# Generated by Django 3.2.3 on 2021-05-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
