# Generated by Django 3.2.3 on 2021-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='discount',
            new_name='offset',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
