# Generated by Django 3.2.3 on 2021-05-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210530_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
